
# ARCHIVUM:        .github/workflows/05-dotnet-action.yml
# LICENTIAM:        Dominium publicum
# SPDX-License-Identifier: Unlicense
# DOCUMENTORUM:     Links:
#                     - https://docs.github.com/pt/actions
#                     - https://github.com/actions/setup-dotnet

name: dotnet-action

on:
  push:
    branches:
      - main

jobs:
  dotnet-action:
    runs-on: ubuntu-latest
    name: Dotnet ${{ matrix.dotnet }} sample
    strategy:
      matrix:
        dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - run: dotnet build programma-exemplum-dotnet.csproj

      - run: dotnet test programma-exemplum-dotnet.csproj
