# SPDX-License-Identifier: Unlicense OR 0BSD

# - https://docs.github.com/pt/actions
# - https://github.com/actions/setup-dotnet

name: dotnet-action

on:
  push:
    branches:
      - main

jobs:
  dotnet-action:
    # runs-on: ubuntu-latest
    runs-on: windows-latest
    name: Dotnet ${{ matrix.dotnet }} sample
    strategy:
      matrix:
        # dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]
        dotnet: [ '5.0.x' ]

    steps:

      #### _____________________________________________________________________
      # _[por-Latn]
      # Passo comum em todo GitHub action: obtem uma cópia do repositório
      # para máquina que esta rodando os testes
      # [por-Latn]_
      - uses: actions/checkout@v2

      #### _____________________________________________________________________
      # @see https://github.com/actions/setup-dotnet
      # @see https://github.com/timheuer/aspnet-core-sample-deploy/blob/master/.github/workflows/build-and-deploy.yml
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - run: dotnet build programma-exemplum-dotnet.csproj

      - run: dotnet test programma-exemplum-dotnet.csproj

      # _[por-Latn]
      # É possível usar GitHub actions para publicar pacotes, e isso envolve
      # usar opões extras documentadas em https://github.com/actions/setup-dotnet
      # A forma como variável NUGET_AUTH_TOKEN é salva pode requerer
      # certos cuidados. Vide
      # https://docs.github.com/pt/actions/security-guides/security-hardening-for-github-actions
      #
      # Caso seu projeto tenha relação com algo humanitário, colaboradores
      # do HXL-CPLP podem ajudar nessa etapa.
      # [por-Latn]_
      - run: dotnet publish programma-exemplum-dotnet.csproj
      # # ./bin/Release/net5.0/programma-exemplum-dotnet
